repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    - id: check-yaml
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-added-large-files
    - id: check-ast
    - id: check-builtin-literals
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-json
    - id: pretty-format-json
    - id: check-merge-conflict
    - id: check-symlinks
    - id: debug-statements
    - id: destroyed-symlinks
    - id: detect-private-key
    - id: mixed-line-ending
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
        args: [--line-length=100]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.800
    hooks:
      - id: mypy
        additional_dependencies: []
